services:
  postgres:
    image: postgres:18
    container_name: incubyte-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: incubyte
      POSTGRES_PASSWORD: incubyte
      POSTGRES_DB: incubyte
    ports:
      - "5432:5432"
    volumes:
      - postgres_18_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incubyte -d incubyte"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_18_data:
